### PR TITLE
Upstream breaking changes

### PR DESCRIPTION
**Pull request by jarohen**
Hey Sean, hope you're keeping well :wave: 

Here's a PR for a few upstream breaking changes - more details in our [dev diary](https://www.xtdb.com/blog/dev-diary-jan-24)

Cheers,

James

### CODE REVIEW

**Comment by seancorfield** [comment]
Can you explain the relationship between `IXtdb` and `IXtdbSubmitClient`? (I looked at the source code briefly and couldn't really figure this out)

Given that `-execute-all*` can submit TXs, it seems that `Executable` should be extended to `IXtdbSubmitClient` specifically instead of `IXtdb`?

**Comment by jarohen** [comment]
It's an old distinction, certainly - in the XT1 days we separated out nodes that indexed and nodes that didn't (before remote nodes existed); you could submit transactions to the latter (i.e. a batch import) but not queries. Not sure whether we'll keep it for v2 (opinions welcome as to whether it's actually useful when XT 2's to be run more often in a client/server mode).

`IXtdb` extends `IXtdbSubmitClient` with the query methods - so it's possible that next.jdbc.xt could just support `IXtdb` and not worry about the difference (edit: updated the PR).

**Comment by seancorfield** [comment]
Thanks. Using `IXtdb` everywhere makes more sense then.

Given the more client/server nature of XT2, I can't see why any users would need the submit-only variant type.

**Comment by seancorfield** [comment]
I've updated the README/CHANGELOG to reflect this PR and the new SHA to use.

**Comment by jarohen** [comment]
Brill, thanks Sean :pray: 

I've also removed the submit-client entirely to avoid this confusion in the future - xtdb/xtdb#3144

**Comment by seancorfield** [comment]
Nice bit of streamlining there. 👍

**Comment by seancorfield** [comment]
I can't get the usermanager example working with this update. It seems that XtdbClient is both `xtdb.api.IXtdb` **and** `clojure.lang.Associative` -- and various `next.jdbc` protocols are already extended to `Associative` so extending them to `IXtdb` creates an ambiguity: sometimes the hash map implementation is picked, sometimes the `IXtdb` implementation is picked (depending on code execution order I think).

That's why the previous `next.jdbc.xt` implementation was so complex by comparison.

I'm going to revert this PR to restore the more discerning type-based implementation, and just make the API-level changes that are needed.

**Comment by seancorfield** [comment]
I got the basics working again -- relying on `xtdb.node.impl` and `xtdb.client.impl` nses but removing the `xtdb.node.impl.SubmitNode` stuff -- but ran into a new problem:
* XTDB now returns results from SQL with `$` mapped to `/` and `_` mapped to `-` which breaks basic round-tripping
* The XTDB version of the usermanager example app is broken due to this, since it assumes unquoted round-tripping

I expect I can "fix" this by forcing all the operations in the usermanager code to use quoting (haven't tested this yet) so I'll probably add `jdbc/xt-opts` as a hash map with `:table-fn` and `:column-fn` both set to `quoted/ansi` and add a note that user code **must** provide that option hash map to the friendly SQL functions... (will probably do that next week).

**Comment by seancorfield** [comment]
I realize that alone won't quite work: `:table/column` is a convention assumed by both HoneySQL and `next.jdbc` so `:xt/id` would still be treated as column `id` in table `xt`, even if I told folks to use the `xt-opts` that handled `:table-fn` and `:column-fn`.

I think it's just very problematic to have the SQL API in XTDB return identifiers that are not legal SQL entities.

**Comment by jarohen** [comment]
Hey Sean :wave: 

> It seems that XtdbClient is both `xtdb.api.IXtdb` and `clojure.lang.Associative` -- and various next.jdbc protocols are already extended to `Associative` so extending them to `IXtdb` creates an ambiguity: sometimes the hash map implementation is picked, sometimes the `IXtdb` implementation is picked (depending on code execution order I think).

Not a general solution, but we may not need `XtdbClient` to be `Associative`, I can take a look. Assuming you can't/would prefer not to extend to something more specific (`IPersistentMap`, I'd guess?) - fair enough if so :slightly_smiling_face:

**Comment by jarohen** [comment]
Regarding the keys: you should now be able to supply `:key-fn` to `xt/q` to get the original identifiers through - this defaults to `:kebab-case-keyword` which is what is making this transformation. Would `:snake-case-string` work for you, for example?

**Comment by seancorfield** [comment]
That's kinda hard to find in the docs :) OK, I am now passing `:key-fn :snake-case-string` into `xt/q` and then calling `walk/keywordize-keys` on the result and now I get back what I "expect". Thank you!

**Comment by jarohen** [comment]
Yep, agreed - thought I'd updated the docs with this one but I hadn't - sorry for the wild goose chase here :man_facepalming:

**Pull request merged**
